### PR TITLE
Including the multi layered character model

### PR DESCRIPTION
**Pull request by TheRyeGuyWhoWillNowDie**
makes the "sunglasses guy" prototype not crash the game lmao

### CODE REVIEW

**Review by nicemicro — CHANGES_REQUESTED** [review]
Nice fix!
The role announcement screen doesn't respect the new characters yet.

**Comment by Damjan94** [comment]
> Nice fix!
> The role announcement screen doesn't respect the new characters yet.

I will fix the role announcement in a few days(I'm busy currently)

as long as I can get the sprites based on player id

**Review by nicemicro — DISMISSED** [review]

**Comment by nicemicro** [comment]
All right, accepted @Damjan94 's promise to fix the role announcement, so this PR can be merged now.

**Comment by TheSecondReal0** [comment]
All commits in this PR have already been merged, closing

**Pull request closed without merging**
