### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by moxvallix**

### CODE REVIEW

**Review by nicemicro — COMMENTED** [review]
The files look good, however, the game doesn't seem to have the Korean characters, so when switching to Korean, every character becomes a little diamond with a question mark in it.

**Comment by GrbavaCigla** [comment]
Is that a font issue? What font are we using?

**Comment by monban** [comment]
The font we're using right now is [Roboto from Google](https://github.com/googlefonts/roboto), I picked it early on just because I generally like the look of it, and it's open source. It was really just kind of "something that worked and looked okay", we certainly don't need to stick with it. If someone has a font they like better, possibly with better Unicode support... PRs are open :smile:

**Comment by monban** [comment]
Just want to follow up on this since there hasn't been any activity recently. Do we want to hold the merge until we can get a font with Hangul support, or merge this now and worry about that later?

**Comment by GrbavaCigla** [comment]
We better merge localizations now, because it isn't issue with translation, it is issue with godot and fonts.

**Review by monban — APPROVED** [review]

**Pull request merged**
