### PR TITLE
Add themes

### PR DESCRIPTION
**Pull request by daniel071**
I applied this theme to all the UI: https://github.com/devmcclu/Iso-Themes
I also changed the background colour to be darker in order to match better with the theme:

### Screenshots:
Screenshot 1
Screenshot 2
Screenshot 3
Screenshot 4

The check boxes are slightly broken, so I will fix that soon.

### CODE REVIEW

**Review by monban — COMMENTED** [review]
Code looks solid, tested and game functions normally.

I personally like the look, but I'd like to get some feedback from someone on the art or branding team if this fits with the look and feel they're going for.

Additionally, should the .fnt font files be made LFS artifacts rather than binary blobs? I'm not an LFS expert so I am soliciting feedback please.

**Comment by GrbavaCigla** [comment]
You have merge conflict, I am reviewing it now.

**Review by monban — APPROVED** [review]
I spoke with the art team leader and he gave the design a :+1:, I have resolved the merge conflict and re-tested, merging now.

**Comment by monban** [comment]
:+1:

**Pull request merged**
