### PR TITLE
Simplify networking code by calling the server from the local client

### PR DESCRIPTION
**Pull request by vainiovano**
The players list of the server (in CLIENT_SERVER mode) now contains the local client (network id 1). The local client operates on the server state directly and the server has to remember not to send extra messages to the local client.

This change could make some things simpler, but I'd like to receive a few comments to know if this change could cause some future problems.

### CODE REVIEW

**Review by TheSecondReal0 — CHANGES_REQUESTED** [review]
Everything looks good to me and it works as intended, but please make sure the settings button is shown in the main menu.

**Comment by vainiovano** [comment]
Is it really broken by this commit?

**Comment by monban** [comment]
Unfortunately, I think this PR has become overcome by events. I really hate to close a PR, especially one with good code, but I think it's irrelevant after the changes @TheSecondReal0 and I recently made to the networking stack. @vainiovano I'll leave it to you if you want to try to rebase and salvage it, or close it and start over. I genuinely hope you don't feel your hard work is being disrespected.

**Comment by vainiovano** [comment]
I agree that this PR isn't relevant any more. I'll create a separate PR for replacing remote with master/puppet in some functions.

**Pull request closed without merging**
