### PR TITLE
removed myself from contributors

### PR DESCRIPTION
**Pull request by literit**
I haven't been with this project for a long time, and am not a contributor.

### CODE REVIEW

**Comment by moxvallix** [comment]
You can add yourself to the hall of fame section if you would like. Format it similarly to the Luke Connor entry. (Hall of Fame is for past members)

**Review by nicemicro — DISMISSED** [review]

**Comment by literit** [comment]
can someone please tell me when my last message was on matrix?

**Comment by moxvallix** [comment]
You left the leaders room on the 5th Dec 2020. IDK about your actual last message, its hard to find.

**Review by moxvallix — APPROVED** [review]
Awesome! Wouldn't want your time with the project left undocumented!

**Pull request merged**
