### PR TITLE
Added splash screen and icon

### PR DESCRIPTION
**Pull request by vincens2005**
opensus
Splash screen ^^

sus_icon

Icon ^^

### CODE REVIEW

**Comment by jgx0** [comment]
Very high quality and makes the game generally better

**Review by Damjan94 — COMMENTED** [review]
couldn't test the icon, as I am on linux, but the splash screen looks good

**Review by nicemicro — DISMISSED** [review]
Looks fine!
Approved.

**Review by nicemicro — COMMENTED** [review]
Shouldn't the xcf file be in misc/images as it is not used directly in the game, but rather, is the source file for the bootsplash pic?

**Review by nicemicro — APPROVED** [review]
Great! Thanks.

**Pull request merged**
