### PR TITLE
Colorblind mode

### PR DESCRIPTION
**Pull request by GrbavaCigla**
Added colorblind shader, added colorblind to settings, made dummy function in settings. When settings system gets comboboxes, it will support all kinds of color blindnesses

### CODE REVIEW

**Comment by TheSecondReal0** [comment]
I would recommend putting the shaders folder in assets/common instead of in assets, just for the sake of organization

**Comment by GrbavaCigla** [comment]
Fixed

**Comment by tooManyArguments** [comment]
Probably due to new merges, please rebase and check again (conflict)

**Comment by GrbavaCigla** [comment]
Will do

**Comment by GrbavaCigla** [comment]
Resolved conflicts

**Comment by vainiovano** [comment]
How would swapping the colors help people with color blindness? Wouldn't it just move the problematic colors?

**Comment by GrbavaCigla** [comment]
I copied the shader from here: https://www.reddit.com/r/gamedev/comments/9u1y6f/adding_colorblind_accessibility_with_an/
It helps, but it isn't ideal

**Review by vainiovano — APPROVED** [review]
Really needs further testing with different colors but approving for now

**Pull request merged**
