### PR TITLE
The host naming thing has been fixed.

### PR DESCRIPTION
**Pull request by TheRyeGuyWhoWillNowDie**
yes

### CODE REVIEW

**Comment by GrbavaCigla** [comment]
Crashes for me

**Comment by TheSecondReal0** [comment]
It crashes for me when joining a server, in _on_main_player_moved(). I recommend adding something like
	if not players.keys().has(id):
		return

**Comment by TheRyeGuyWhoWillNowDie** [comment]
hey guys there is no issue whatsoever, re export your client because it's old

**Review by TheSecondReal0 — APPROVED** [review]
Host naming has been fixed and there are no obvious bugs

**Pull request merged**
