### PR TITLE
New assets, with 100% more LFS

### PR DESCRIPTION
**Pull request by TheRyeGuyWhoWillNowDie**
sooo please dont submit prs with new assets unless you have lfs

### CODE REVIEW

**Review by tooManyArguments — APPROVED** [review]
Looked through, cloned, test played - OK

**Review by moxvallix — APPROVED** [review]
Cloned it down, seems good!

**Comment by MGThePro** [comment]
make sure to set `flags/filter` to `false` in the import files, otherwise the pixelart will be blurred when scaling

**Comment by tooManyArguments** [comment]
as MGThePro stated, please make a new commit where you change all the : 
`flags/filter=true` lines in the .import files (or in the gui)

**Review by tooManyArguments — CHANGES_REQUESTED** [review]
change filter/flags in .import files as discussed in comments

**Comment by TheRyeGuyWhoWillNowDie** [comment]
making new pr, disabling filter

**Pull request closed without merging**
