### PR TITLE
Fixed section breaking translations (for now)

### PR DESCRIPTION
**Pull request by GrbavaCigla**
This fixes new settings section system breaking localization. This is not the best solution, but I will fix it when I make full section support.

### CODE REVIEW

**Review by nicemicro — DISMISSED** [review]
Although the translations are spotty, it seems to be a move in the right direction.

**Comment by vainiovano** [comment]
I think that settings shouldn't be locale-dependent. I recommend doing something like this:
```diff
diff --git a/src/assets/ui/submenus/settings/settings.gd b/src/assets/ui/submenus/settings/settings.gd
index 896ab50..f00a2b5 100644
--- a/src/assets/ui/submenus/settings/settings.gd
+++ b/src/assets/ui/submenus/settings/settings.gd
@@ -31,9 +31,9 @@ class Setting:
 		if '/' in text:
 			var raw_label = text.rsplit('/', true, 1)
 			self.section = raw_label[0]
-			self.text = raw_label[1]
+			self.text = tr(raw_label[1])
 		else:
-			self.text = text
+			self.text = tr(text)
 			self.section = "general"
 
 		if type == SettingType.OPTION:
@@ -59,12 +59,12 @@ func dummy_function(setting):
 
 
 var settings = [
-	Setting.new(true, SettingType.SWITCH, tr("Video")+"/"+tr("Fullscreen"), "toggle_fullscreen"),
+	Setting.new(true, SettingType.SWITCH, "Video/Fullscreen", "toggle_fullscreen"),
 	Setting.new(
-		0, SettingType.OPTION, tr("Video")+"/"+tr("Colorblind mode"), "dummy_function", ["RGB", "GBR", "BRG", "BGR"]
+		0, SettingType.OPTION, "Video/Colorblind mode", "dummy_function", ["RGB", "GBR", "BRG", "BGR"]
 	),
-	Setting.new(30, SettingType.SLIDER, tr("Sound")+"/"+("Volume"), "dummy_function"),
-	Setting.new(0, SettingType.OPTION, tr("Locale")+"/"+tr("Language"), "set_language", get_languages())
+	Setting.new(30, SettingType.SLIDER, "Sound/Volume", "dummy_function"),
+	Setting.new(0, SettingType.OPTION, "Locale/Language", "set_language", get_languages())
 ]
```

**Comment by vainiovano** [comment]
And Godot seems to have problems with character encodings (my config file now contains a line of `video/plein_Ã<U+0083>Â<U+0083>Ã<U+0082>Â<U+0083>Ã<U+0083>Â<U+0082>Ã<U+0082>Â©cran=false`)

**Comment by GrbavaCigla** [comment]
> I think that settings shouldn't be locale-dependent. I recommend doing something like this:
> 
> ```diff
> diff --git a/src/assets/ui/submenus/settings/settings.gd b/src/assets/ui/submenus/settings/settings.gd
> index 896ab50..f00a2b5 100644
> --- a/src/assets/ui/submenus/settings/settings.gd
> +++ b/src/assets/ui/submenus/settings/settings.gd
> @@ -31,9 +31,9 @@ class Setting:
>  		if '/' in text:
>  			var raw_label = text.rsplit('/', true, 1)
>  			self.section = raw_label[0]
> -			self.text = raw_label[1]
> +			self.text = tr(raw_label[1])
>  		else:
> -			self.text = text
> +			self.text = tr(text)
>  			self.section = "general"
>  
>  		if type == SettingType.OPTION:
> @@ -59,12 +59,12 @@ func dummy_function(setting):
>  
>  
>  var settings = [
> -	Setting.new(true, SettingType.SWITCH, tr("Video")+"/"+tr("Fullscreen"), "toggle_fullscreen"),
> +	Setting.new(true, SettingType.SWITCH, "Video/Fullscreen", "toggle_fullscreen"),
>  	Setting.new(
> -		0, SettingType.OPTION, tr("Video")+"/"+tr("Colorblind mode"), "dummy_function", ["RGB", "GBR", "BRG", "BGR"]
> +		0, SettingType.OPTION, "Video/Colorblind mode", "dummy_function", ["RGB", "GBR", "BRG", "BGR"]
>  	),
> -	Setting.new(30, SettingType.SLIDER, tr("Sound")+"/"+("Volume"), "dummy_function"),
> -	Setting.new(0, SettingType.OPTION, tr("Locale")+"/"+tr("Language"), "set_language", get_languages())
> +	Setting.new(30, SettingType.SLIDER, "Sound/Volume", "dummy_function"),
> +	Setting.new(0, SettingType.OPTION, "Locale/Language", "set_language", get_languages())
>  ]
> ```

That cannot be done. That will work until you update the localizations. tr function must have string inside to be able to generate localization. I thought about this, but you would have to do everything manually.

**Comment by GrbavaCigla** [comment]
> And Godot seems to have problems with character encodings (my config file now contains a line of `video/plein_Ã<U+0083>Â<U+0083>Ã<U+0082>Â<U+0083>Ã<U+0083>Â<U+0082>Ã<U+0082>Â©cran=false`)

Isn't the case for me. I fixed this issue a while ago. When I clean run opensuspect it works. As i said, I am going to rework settings

**Review by vainiovano — APPROVED** [review]
This is ugly and a bit broken, but I don't know a better way to do this with the current setting system without duplicating strings

**Pull request merged**
