### PR TITLE
Role announcement fix

### PR DESCRIPTION
**Pull request by Damjan94**
I saw in chat that someone wanted to make a dedicated function for getting the player preview sprites, so I just copied the code that was in role announcement script to PlayerManager

### CODE REVIEW

**Review by nicemicro — CHANGES_REQUESTED** [review]
Have no idea why, but the game doesn't start after clicking "Create".

**Comment by Damjan94** [comment]
> Have no idea why, but the game doesn't start after clicking "Create".

I forgot to add a file to git. it should work now

**Review by nicemicro — DISMISSED** [review]
It doesn't break anymore, and can be merged to main with no conflicts, however the skintones don't yet appear on the role announcement screens, and due to the limitations of the character customization stuff, I am not a 100% sure if it does what it says it does.

**Comment by Damjan94** [comment]
ok, I have made it work with skin tones

**Review by jngo102 — CHANGES_REQUESTED** [review]
I'm still not seeing players in the role announcement screen when starting a game in full screen.

**Pull request closed without merging**
