### PR TITLE
Runtime player spawning and respawning

### PR DESCRIPTION
**Pull request by TheSecondReal0**
All players are now created at runtime, including the host. All player nodes are now deleted and recreated upon map switch.

### CODE REVIEW

**Review by vainiovano — DISMISSED** [review]
Looks great!

Some notes:
- Spawning new players to the lobby uses only one spawn point. A better collision-based system can be implemented in the future
- The old spawning code and `spawned` array could be removed

**Comment by nicemicro** [comment]
>     * The old spawning code and `spawned` array could be removed

I'd suggest this being fixed before the PR is merged.

**Comment by vainiovano** [comment]
The players still have a `spawned` array that's unused

**Review by vainiovano — APPROVED** [review]
Looks good, works well

**Pull request merged**
